should fail unit test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -27,3 +27,10 @@ jobs:
       run: |
         python -m pytest --exitfirst src/envs/stock/graph_unittests.py
         python -m pytest --exitfirst src/envs/stock/trader_unittests.py
+
+    - name: Check for test failures
+      run: |
+        if [ -f pytest.failures ]; then
+          echo "Test failures detected."
+          exit 1
+        fi
